### ISSUE TITLE
Configure Home Assistant to receive image

### ISSUE THREAD

**Issue by goermezer** [psyciknz/CameraEvents#11]
Do anybody know, how I have to configure home assistant to receive the image, which is sent by CameraEvents?

My Payload looks like documented:

`{"message": "IVS: Dahua3: CrossRegionDetection", "imagebase64": "/9j/4AAQSkZJRgA..."}`

My configuration:

```
camera:
  - platform: mqtt
    topic: CameraEvents/Dahua3/Image
    name: my mqtt camera image
```

When the image is sent by CameraEvents, the sensor in home assistant shows idle the whole time and nothing is logged. I think, I have to reference the imagebase64 attribute. But I don`t know how. Anybody have success with a camera mqtt sensor in home assistant?
